### ISSUE TITLE
Build all product and intermediate/dependencies images from source

### ISSUE THREAD

**Issue by maltesander** [stackabletech/docker-images#674]
In order to have more control over the products in terms of adding / removing / excluding libraries, modules etc. and improve CVE handling, we want to build all our products from source.

```[tasklist]
### Products
- [ ] ~~Airflow~~ (out of scope for now)
- [ ] ~~Superset~~ (out of scope for now)
- [ ] https://github.com/stackabletech/docker-images/pull/684
- [ ] https://github.com/stackabletech/docker-images/pull/687
- [ ] https://github.com/stackabletech/docker-images/pull/494
- [ ] https://github.com/stackabletech/docker-images/pull/526
- [ ] https://github.com/stackabletech/docker-images/pull/581
- [ ] https://github.com/stackabletech/docker-images/pull/659
- [ ] https://github.com/stackabletech/docker-images/pull/678
- [ ] https://github.com/stackabletech/docker-images/pull/685
- [ ] https://github.com/stackabletech/docker-images/pull/679
- [ ] https://github.com/stackabletech/docker-images/pull/638
- [ ] https://github.com/stackabletech/docker-images/pull/676
```

```[tasklist]
### Intermediate images
- [ ] https://github.com/stackabletech/docker-images/pull/658
```

```[tasklist]
### Miscellaneous (out of scope here, just for completeness)
- [ ] krb5 -> no
- [ ] vector
- [ ] statsd-exporter
- [ ] jmx-exporter
- [ ] kafka-opa-authorizer
- [ ] other jars like stax2-api, woodstox, jackson..
```

**Comment by maltesander** [comment]
All done!
