### ISSUE TITLE
chore: Update Container Images for Stackable Release 24.11

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/docker-images#798]
## Container Image Updates for Stackable Release 24.11

> [!NOTE]
> Update the product versions based on what has been decided upon in the _Product Spreadsheet[^1]_.

[^1]: Currently this is a private spreadsheet

Replace the items in the task lists below with the applicable Pull Requests

```[tasklist]
### Product Container Images
- [ ] https://github.com/stackabletech/docker-images/tree/main/airflow/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/druid/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/hadoop/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/hbase/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/hello-world/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/hive/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/java-base/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/java-devel/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/kafka/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/kafka-testing-tools/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/kcat/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/krb5/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/nifi/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/omid/versions.py
- [ ] https://github.com/stackabletech/docker-images/pull/797
- [ ] https://github.com/stackabletech/opa-operator/pull/616
- [ ] https://github.com/stackabletech/demos/pull/85
- [ ] https://github.com/stackabletech/docker-images/tree/main/spark-k8s/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/stackable-base/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/superset/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/testing-tools/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/tools/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/trino/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/trino-cli/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/vector/versions.py
- [ ] https://github.com/stackabletech/docker-images/tree/main/zookeeper/versions.py
```

> [!NOTE]
> Generally you will only need to update the rust-toolchain version (`RUST_DEFAULT_TOOLCHAIN_VERSION`).

```[tasklist]
### Other Container Images
- [ ] https://github.com/stackabletech/docker-images/tree/main/ubi8-rust-builder/Dockerfile
- [ ] https://github.com/stackabletech/docker-images/tree/main/ubi9-rust-builder/Dockerfile
```

**Comment by NickLarsenNZ** [comment]
Closing in favor of https://github.com/stackabletech/issues/issues/626
