### ISSUE TITLE
chore: Update Container Images for Stackable Release 24.11

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/docker-images#831]
Part of stackabletech/issues#647.

> [!IMPORTANT]
> **Supersedes https://github.com/stackabletech/issues/issues/626**
>
> Some of the work has already been done in that issue, so the tasklist below will link back to that.
> After the meeting on 11/09 where we lock the versions, there might be minor bumps. The templates can be used from there, and links updated below.

## Container Image Updates for Stackable Release 24.11

> [!NOTE]
> Update the product versions based on what has been decided upon in the _Product Spreadsheet[^1]_.

[^1]: Currently this is a private spreadsheet

Replace the items in the task lists below with the subsequent tracking issue.

```[tasklist]
### Product Container Images
- [x] No additional Java versions to add (22 is the latest)
- [x] stackable-base https://github.com/stackabletech/issues/issues/626
- [x] ubi-rust-builders https://github.com/stackabletech/issues/issues/626
- [ ] https://github.com/stackabletech/docker-images/issues/845
- [ ] https://github.com/stackabletech/docker-images/issues/847
- [ ] https://github.com/stackabletech/docker-images/issues/833
- [ ] https://github.com/stackabletech/docker-images/issues/834
- [ ] https://github.com/stackabletech/docker-images/issues/835
- [x] hive https://github.com/stackabletech/issues/issues/626
- [x] kafka https://github.com/stackabletech/issues/issues/626
- [ ] https://github.com/stackabletech/docker-images/issues/836
- [x] opa https://github.com/stackabletech/issues/issues/626
- [ ] https://github.com/stackabletech/docker-images/issues/838
- [ ] https://github.com/stackabletech/docker-images/issues/837
- [x] trino https://github.com/stackabletech/issues/issues/626
- [ ] https://github.com/stackabletech/docker-images/issues/832
```

```[tasklist]
### Additional items which don't have a tracking issue
- [x] hello-world - ~bump to java 22/23?~
- [x] krb5 - no change
- [ ] https://github.com/stackabletech/docker-images/pull/896
- [x] testing-tools - no change
- [x] statsd_exporter (will be bumped to `1.27.0` in #837)
- [ ] https://github.com/stackabletech/docker-images/pull/879
```

**Comment by NickLarsenNZ** [comment]
Use https://github.com/stackabletech/docker-images/issues/831 from now on

**Comment by NickLarsenNZ** [comment]
Update: I'm checking the versions in docker-images match what was listed in the spreadsheet.

**Comment by NickLarsenNZ** [comment]
Checks are done
