### ISSUE TITLE
chore(vector): Update container images ahead of Stackable Release 24.11

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/docker-images#845]
Part of #831.

Upgrade to Vector 0.41.1, see #795.

> [!TIP]
> Please add the `scheduled-for/20XX-XX` label.

> [!IMPORTANT]
>
> - Uses [stackable-base](https://github.com/stackabletech/docker-images/blob/main/stackable-base/Dockerfile).
> - Used as a base for [java-base](https://github.com/stackabletech/docker-images/blob/main/java-base/Dockerfile).

```[tasklist]
### Update tasks
- [x] Update `versions.py` to reflect the agreed upon versions in the spreadsheet (including the removal of old versions).
- [x] Update all `versions.py` files which reference vector.
- [x] Upload new version (see `vector/upload_new_vector_version.sh`).
- [x] Update other dependencies if applicable (eg: inotify_tools, etc).
- [x] Check other operators (getting_started / kuttl) for usage of the versions. Add the PR(s) to the list below.
- [x] Update the version in demos. Add the PR(s) to the list below.
```

```[tasklist]
### Related Pull Requests
- [ ] #867 
- [ ] stackabletech/airflow-operator#506 
- [ ] stackabletech/druid-operator#626
- [ ] stackabletech/hbase-operator#564
- [ ] stackabletech/hdfs-operator#583
- [ ] stackabletech/hive-operator#514
- [ ] stackabletech/kafka-operator#758
- [ ] stackabletech/nifi-operator#678
- [ ] stackabletech/opa-operator#628
- [ ] stackabletech/spark-k8s-operator#467
- [ ] stackabletech/superset-operator#541
- [ ] stackabletech/trino-operator#644
- [ ] stackabletech/zookeeper-operator#861
- [ ] stackabletech/demos#101
```

```[tasklist]
### Acceptance
- [ ] Can build image locally
- [ ] Kuttl smoke tests passes locally
- [ ] Release notes written in a comment below
- [ ] Applicable `release-note` label added to this issue
```

<details>
<summary>Testing instructions</summary>

```shell
# See the latest version at https://pypi.org/project/image-tools-stackabletech/
pip install image-tools-stackabletech==0.0.12

bake --product vector=x.y.z # where x.y.z is the new version added in this PR

kind load docker-image docker.stackable.tech/stackable/vector:x.y.z-stackable0.0.0-dev

# Change directory into one of the operator repositories and update the
# product version in tests/test-definition.yaml
./scripts/run-tests --test-suite smoke-latest # or similar
```

</details>

_Please consider updating this template if these instructions are wrong, or
could be made clearer._

**Comment by NickLarsenNZ** [comment]
FYI

- https://github.com/stackabletech/docker-images/pull/802 (bump to 0.40.0)
  - Kuttl tests for operators were bumped to this version.
- https://github.com/stackabletech/docker-images/pull/815 (bump to 0.40.1 to fix a regression)
  - Kuttl tests for operators were not yet bumped to this version.
